version: '3.9'
services:
  keycloak:
    image: keycloak/keycloak:25.0
    ports:
      - "8080:8080"
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE=default
    networks:
      - aurora-network
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
  
networks:
  aurora-network:
    driver: bridge
  
volumes:
  keycloak_data:
    driver: local
